version: '3.4'

services:
  app:
    container_name: nestjs_api_dev
    image: nestjs-api-dev:0.0.1
    build:
      context: .
      target: development
      dockerfile: ./Dockerfile
    command: npm run start:dev
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
    links:
      - mongodb
  mongodb:
    container_name: mongo_db
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    volumes:
      - data-volume:/data/db
  mongo-seed:
    build: ./mongo-seed
    links:
      - mongodb
volumes:
  data-volume: