export type TSevices = {
  USER_SERVICE: 'USER_SERVICE';
  AUTH_SERVICE: 'AUTH_SERVICE';
  LOGGER_SERVICE: 'LOGGER_SERVICE';
};

export const SERVICES: TSevices = {
  USER_SERVICE: 'USER_SERVICE',
  AUTH_SERVICE: 'AUTH_SERVICE',
  LOGGER_SERVICE: 'LOGGER_SERVICE',
};
